In [2]:
import numpy as np

In [13]:
a = np.array([[10,15]])
b = np.array([[20,9]])
print(a)
print(b)
print()

# add transpose
(a + b).T

[[10 15]]
[[20  9]]



array([[30],
       [24]])

In [14]:
# subtract
a - b

array([[-10,   6]])

In [16]:
# scaler
a = 2
u = np.array([[30,15]])

a * u

array([[60, 30]])

In [23]:
# dot product

u = np.array([10,20])
v = np.array([25,6])

print(10*25 + 20*6)
np.dot(u,v)

370


370

In [28]:
# matrix addition
a = np.array([[10,15], [2,1], [3,1]])
b = np.array([[20,9], [2,1], [3,1]])

print(a, end ="\n\n")
print(b)

[[10 15]
 [ 2  1]
 [ 3  1]] 

[[20  9]
 [ 2  1]
 [ 3  1]]


In [29]:
# matrix subtraction
a-b

array([[-10,   6],
       [  0,   0],
       [  0,   0]])

In [30]:
# matrix and vector multiplication

a = [[5,10], [15,20]]
b = [10,12]

np.dot(a,b)

array([170, 390])

In [38]:
# empty matrix
a = np.full(shape=[5,5], fill_value=None)
a[1,1] = 2
a

array([[None, None, None, None, None],
       [None, 2, None, None, None],
       [None, None, None, None, None],
       [None, None, None, None, None],
       [None, None, None, None, None]], dtype=object)

In [40]:
# identity matrix

i1 = np.eye(2)  # 2x2 matrix
i1

array([[1., 0.],
       [0., 1.]])

In [42]:
# inverse
a = np.array([[10,15,2], [2,1,1], [3,1,1]])
print(a)
print(np.linalg.inv(a))


[[10 15  2]
 [ 2  1  1]
 [ 3  1  1]]
[[ 2.22044605e-17 -1.00000000e+00  1.00000000e+00]
 [ 7.69230769e-02  3.07692308e-01 -4.61538462e-01]
 [-7.69230769e-02  2.69230769e+00 -1.53846154e+00]]
